config/routes.rb
Rails.application.routes.draw do
  #  get 'users/create'
  post 'users', to: 'users#create'
  root 'home#index'

  #NUEVAS RUTAS
  post :add, to: 'calculator#compute_add'
  get :add, to: 'calculator#add' , as: 'sumar'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true
    validates :email, presence: true
    validates :email, uniqueness: { scope: :email }

    enum state: ["propuesta","en progreso", "terminado"]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calculator_controller.rb
class CalculatorController < ApplicationController
    # sólo muestra el formulario
        def add
        end

        def compute_add
            first = params[:first].to_i
            last = params[:last].to_i
            @total = first + last
        end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # skip_before_action :verify_authenticity_token, on: [:create]
  def create
    # byebug
    @user = User.create(
        email: params[:email],
        name: params[:name]
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/calculator/add.html.erb
<%= form_tag(add_path, method: "post", class:"container") do %>
    <div class="form-group">
        <%= label_tag(:first, "Primer número") %>
        <%= text_field_tag(:first , nil, class: 'form-control') %>
    </div>
    <div class="form-group">
        <%= label_tag(:last, "Segundo número") %>
        <%= text_field_tag(:last, nil, class: 'form-control') %>
    </div>
    <%= submit_tag("Sumar", class: 'btn btn-primary') %>
<% end %>

app/views/calculator/compute_add.html.erb
<div>
    <p>El resultado de la suma es <%= @total %></p>
</div>
<%= link_to "Volver a sumar", sumar_path %>

app/views/home/index.html.erb
<form action="<%= users_path  %>" method="post" class="container" id="create_users">
  <%= token_tag %>
  <div class="form-group">
    <label for="email">Email</label>
    <input name="email" type="email" class="form-control" id="email" required>
  </div>
  <div class="form-group">
    <label for="name">Name</label>
    <input name="name" type="text" class="form-control" id="name">
  </div>

  <button type="submit" class="btn btn-primary">Enviar</button>
</form>


<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Email</th>
      <th scope="col">Name</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
        <tr>
            <th scope="row"><%= user.id %></th>
            <td><%= user.email %></td>
            <td><%= user.name %></td>
        </tr>
    <% end %>
   </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrudUsers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<% if @user.errors.any? %>
 <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being
    saved:</h2>
    <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
 </div>
<% else %>
 <h1>Exito !!!! </h1>
 <%= link_to 'Home', root_path  %>
<% end %>